### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by j-woz**

### CODE REVIEW

**Review by jmohdyusof — COMMENTED** [review]
In parsing_utils ckpt_directory default to None but in keras_utils it defaults to './'?

**Comment by j-woz** [comment]
Do you mean in ckpt_utils ?

**Comment by jmohdyusof** [comment]
I guess so. In any case, they are inconsistent

**Review by jmohdyusof — APPROVED** [review]
Ckpt_utils is correct, need to review data_dir and output_dir defaults elsewhere.

**Pull request merged**
